<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260822095543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_client VARCHAR(255) NOT NULL, email_client VARCHAR(255) NOT NULL, telephone_client VARCHAR(30) DEFAULT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(20) NOT NULL, jour_retrait_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67D3135D4DF ON commande (jour_retrait_id)');
        $this->addSql('CREATE TABLE jour_retrait (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jour VARCHAR(20) NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_jour ON jour_retrait (jour)');
        $this->addSql('CREATE TABLE ligne_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire NUMERIC(10, 2) NOT NULL, commande_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3170B74B82EA2E54 ON ligne_commande (commande_id)');
        $this->addSql('CREATE INDEX IDX_3170B74BF347EFB ON ligne_commande (produit_id)');
        $this->addSql('CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, prix NUMERIC(10, 2) NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stock_produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stock_initial INT NOT NULL, stock_restant INT NOT NULL, produit_id INT NOT NULL, jour_retrait_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3003FC84F347EFB ON stock_produit (produit_id)');
        $this->addSql('CREATE INDEX IDX_3003FC843135D4DF ON stock_produit (jour_retrait_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_produit_jour ON stock_produit (produit_id, jour_retrait_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_email ON utilisateur (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D3135D4DF FOREIGN KEY (jour_retrait_id) REFERENCES jour_retrait (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74BF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_produit ADD CONSTRAINT FK_3003FC84F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_produit ADD CONSTRAINT FK_3003FC843135D4DF FOREIGN KEY (jour_retrait_id) REFERENCES jour_retrait (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D3135D4DF');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B82EA2E54');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74BF347EFB');
        $this->addSql('ALTER TABLE stock_produit DROP CONSTRAINT FK_3003FC84F347EFB');
        $this->addSql('ALTER TABLE stock_produit DROP CONSTRAINT FK_3003FC843135D4DF');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE jour_retrait');
        $this->addSql('DROP TABLE ligne_commande');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE stock_produit');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
